#Environmental Variable

#server
server:
  port: 8093
  servlet:
    context-path: /client

#database
spring:
  datasource:
    username: sangria
    password: sangria
    url: jdbc:mysql://35.196.112.19:3306/comsw4156?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    

#sql log
logging:
  file:
    path: ./logs
  level:
    com:
      sangria:
        auth:
          mapper : debug

Service:
  ip: 127.0.0.1
  auth:
    port: 8091
    context: auth
    apis:
      register: gameManager/register
      login: gameManager/login
      token: gameManager/token
      info: gameManager/info
      delete: gameManager/delete
      logout: gameManager/logout
  operation:
    port: 8092
    context: operation
    apis:
      freeze: player/freeze
      info: player/info
      removeMoney: player/removeMoney
      sellItemSys: player/sellItemSys
      trade: player/trade
      unfreeze: player/unfreeze
      buyItemSys: player/buyItemSys
      deletePlayer: player/deletePlayer
      inventoryAdd: inventory/add
      inventoryClear: inventory/clear
      inventoryInfo: inventory/info
      itemAdd: item/add
      itemInfo: item/info
      itemMake: item/make
      addMoney: player/addMoney
      playerAdd: player/add
      playerItemAdd: player/addItem
      playerItemRemove: player/removeItem
    
    
          